import React, { useState, useEffect } from 'react';
import {
  Table,
  Button,
  Modal,
  Form,
  Input,
  DatePicker,
  Select,
  message,
  Space,
  Popconfirm,
  Tag,
} from 'antd';
import { DeleteOutlined, CheckOutlined, CloseOutlined } from '@ant-design/icons';
import api from '../../api/axios';
import dayjs from 'dayjs';
import { useOrganizationScope } from '../../hooks/useOrganizationScope';

interface PayrollGeneration {
  id: number;
  organizationId?: number | null;
  monthYear: string;
  generatedBy: string;
  approvedBy: string | null;
  status: string;
  rejectionReason: string | null;
  createdAt: string;
  updatedAt: string;
}

const PayrollGeneration: React.FC = () => {
  const {
    organizationId,
    setSelectedOrganizationId,
    organizations,
    needsOrganizationSelection,
  } = useOrganizationScope();
  const [payrolls, setPayrolls] = useState<PayrollGeneration[]>([]);
  const [loading, setLoading] = useState(false);
  const [modalVisible, setModalVisible] = useState(false);
  const [form] = Form.useForm();
  const [editingId, setEditingId] = useState<number | null>(null);
  const [rejectModalVisible, setRejectModalVisible] = useState(false);
  const [selectedPayrollId, setSelectedPayrollId] = useState<number | null>(null);

  useEffect(() => {
    if (organizationId == null) {
      setPayrolls([]);
      return;
    }
    fetchPayrolls();
  }, [organizationId]);

  const fetchPayrolls = async () => {
    if (organizationId == null) {
      return;
    }
    try {
      setLoading(true);
      const response = await api.get('/api/payroll', {
        params: { organizationId },
      });
      setPayrolls(response.data);
    } catch (error) {
      message.error('Failed to fetch payrolls');
    } finally {
      setLoading(false);
    }
  };

  const handleGenerate = () => {
    setEditingId(null);
    form.resetFields();
    setModalVisible(true);
  };

  const handleApprove = async (id: number) => {
    try {
      const user = JSON.parse(localStorage.getItem('user') || '{}');
      const approvedBy = encodeURIComponent(`${user.firstName} ${user.lastName}`);
      await api.post(`/api/payroll/${id}/approve?approvedBy=${approvedBy}`);
      message.success('Payroll approved successfully');
      fetchPayrolls();
    } catch (error) {
      message.error('Failed to approve payroll');
    }
  };

  const handleReject = async (values: { rejectionReason: string }) => {
    if (!selectedPayrollId) return;

    try {
      await api.post(`/api/payroll/${selectedPayrollId}/reject`, null, {
        params: {
          approvedBy: localStorage.getItem('username') ?? '',
          rejectionReason: values.rejectionReason,
        },
      });
      message.success('Payroll rejected successfully');
      setRejectModalVisible(false);
      fetchPayrolls();
    } catch (error) {
      message.error('Failed to reject payroll');
    }
  };

  const handleDelete = async (id: number) => {
    try {
      await api.delete(`/api/payroll/${id}`);
      message.success('Payroll deleted successfully');
      fetchPayrolls();
    } catch (error) {
      message.error('Failed to delete payroll');
    }
  };

  const handleSubmit = async (values: any) => {
    if (organizationId == null) {
      message.error('Select an organization first');
      return;
    }
    try {
      const monthYear = values.monthYear.format('YYYY-MM');
      await api.post('/api/payroll/generate', null, {
        params: {
          monthYear,
          generatedBy: localStorage.getItem('username') ?? '',
          organizationId,
        },
      });
      message.success('Payroll generated successfully');
      setModalVisible(false);
      fetchPayrolls();
    } catch (error) {
      message.error('Failed to generate payroll');
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'DRAFT':
        return 'blue';
      case 'APPROVED':
        return 'green';
      case 'REJECTED':
        return 'red';
      default:
        return 'default';
    }
  };

  const columns = [
    {
      title: 'Month/Year',
      dataIndex: 'monthYear',
      key: 'monthYear',
      render: (value: string) => dayjs(value).format('MMMM YYYY'),
    },
    {
      title: 'Generated By',
      dataIndex: 'generatedBy',
      key: 'generatedBy',
    },
    {
      title: 'Approved By',
      dataIndex: 'approvedBy',
      key: 'approvedBy',
      render: (value: string | null) => value || '-',
    },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
      render: (value: string) => (
        <Tag color={getStatusColor(value)}>{value}</Tag>
      ),
    },
    {
      title: 'Created At',
      dataIndex: 'createdAt',
      key: 'createdAt',
      render: (value: string) => dayjs(value).format('YYYY-MM-DD HH:mm'),
    },
    {
      title: 'Actions',
      key: 'actions',
      render: (_: any, record: PayrollGeneration) => (
        <Space>
          {record.status === 'DRAFT' && (
            <>
              <Button
                type="primary"
                icon={<CheckOutlined />}
                onClick={() => handleApprove(record.id)}
              >
                Approve
              </Button>
              <Button
                type="primary"
                danger
                icon={<CloseOutlined />}
                onClick={() => {
                  setSelectedPayrollId(record.id);
                  setRejectModalVisible(true);
                }}
              >
                Reject
              </Button>
            </>
          )}
          <Popconfirm
            title="Are you sure you want to delete this payroll?"
            onConfirm={() => handleDelete(record.id)}
          >
            <Button type="primary" danger icon={<DeleteOutlined />}>
              Delete
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <div className="p-6">
      <div className="flex justify-between mb-4">
        <h1 className="text-2xl font-bold">Payroll Generation</h1>
        <Button
          type="primary"
          onClick={handleGenerate}
          disabled={organizationId == null}
        >
          Generate Payroll
        </Button>
      </div>
      {needsOrganizationSelection && (
        <div className="mb-4 flex flex-wrap items-center gap-2">
          <span className="text-sm text-slate-600">Organization</span>
          <Select
            style={{ minWidth: 220 }}
            placeholder="Select organization"
            value={organizationId ?? undefined}
            onChange={(v) => setSelectedOrganizationId(v)}
            options={organizations.map((o) => ({ label: o.name, value: o.id }))}
          />
        </div>
      )}

      <Table
        columns={columns}
        dataSource={payrolls}
        loading={loading}
        rowKey="id"
      />

      <Modal
        title="Generate Payroll"
        open={modalVisible}
        onCancel={() => setModalVisible(false)}
        footer={null}
      >
        <Form
          form={form}
          layout="vertical"
          onFinish={handleSubmit}
        >
          <Form.Item
            name="monthYear"
            label="Month/Year"
            rules={[{ required: true }]}
          >
            <DatePicker
              picker="month"
              style={{ width: '100%' }}
            />
          </Form.Item>

          <Form.Item>
            <Space>
              <Button type="primary" htmlType="submit">
                Generate
              </Button>
              <Button onClick={() => setModalVisible(false)}>
                Cancel
              </Button>
            </Space>
          </Form.Item>
        </Form>
      </Modal>

      <Modal
        title="Reject Payroll"
        open={rejectModalVisible}
        onCancel={() => setRejectModalVisible(false)}
        footer={null}
      >
        <Form
          layout="vertical"
          onFinish={handleReject}
        >
          <Form.Item
            name="rejectionReason"
            label="Rejection Reason"
            rules={[{ required: true }]}
          >
            <Input.TextArea rows={4} />
          </Form.Item>

          <Form.Item>
            <Space>
              <Button type="primary" htmlType="submit">
                Reject
              </Button>
              <Button onClick={() => setRejectModalVisible(false)}>
                Cancel
              </Button>
            </Space>
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default PayrollGeneration; 